---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"LES 3 ACTES (ou 3 OPÉRATIONS) DE L'INTELLIGENCE":::menthe
  "LA COMPRÉHENSION OU SIMPLE APPRÉHENSION":::azul
    "CLAIRE ou CONFUSE"
      "Concept":20:::turquoise
      "Terme":20:::bleu
      "Mot":20:::ardoise
  "LE JUGEMENT":::menthe
    "VRAI ou FAUX"
      "Jugement":20:::turquoise
      "Proposition":20:::bleu
      "Phrase":20:::ardoise
  "LE RAISONNEMENT":::orange
    "VALIDE ou INVALIDE"
      "Raisonnement":20:::orange
      "Argument":20:::ocre
      "Paragraphe":20:::ardoise

classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
