---
config:
  theme: forest
  themeVariables:
    fontFamily: verdana
---
timeline
    title Agenda des notions au programme
    section Septembre -> Vacances de la Toussaint
        Introduction : Bonheur : Justice : Liberté : Raison : Vérité : Méthode de dissertation
        Philosophie de la connaissance : Raison : Langage : Nature : Vérité : Science
        Philosophie morale : Liberté : Bonheur : Nature
    section Novembre -> Vacances de Noël
        Philosophie morale : Conscience : Bonheur : Nature : Devoir
    section Janvier -> Vacances d'hiver
        Philosophie politique : Méthode d'étude ordonnée : Inconscient : Religion : État : Justice 
    section Mars -> Vacances de printemps
        Philosophie de l'existence humaine et de la culture : Temps : Langage : Considérations morales d'Hannah ARENDT : Nature : Travail : Technique
    section Mai -> Libération
        Philosophie de l'existence humaine et de la culture : Technique : Art
        Révisions : Philosophie de la connaissance : Philosophie morale : Philosophe politique : Philosophie de l'existence humaine
        Bac
