---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"RÉPARTITION DES CROYANCES DES PHILOSOPHES AU PROGRAMME DE TERMINALE":::menthe
  "11 PAÏENS":11:::ocre
  "1 B":1%% Bouddhistes
  "1 T":1%% Taoïstes
  "27 CHRÉTIENS":::azul
    "CHRÉTIENS":4:::azul
    "CATHOLIQUES":11:::bleu
    "ANGLICANS":5:::ardoise
    "PROTESTANTS":7:::turquoise
  "11 JUIFS":11:::bleu
  "2 M":2:::turquoise%% Musulmans
  "1 P":1:::menthe%% Panthéistes
  "15 ATHÉES":::orange
    "ATHÉES":10:::orange
    "MATÉRIALISTES":5:::ardoise
  "14 AGNOSTIQUES":14:::menthe
classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
