---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"RÉPARTITION DES CROYANCES DES PHILOSOPHES DE L'ANTIQUITÉ AU PROGRAMME DE TERMINALE":::menthe
  "11 PAÏENS":11:::ocre
  "1B":1%% Bouddhistes
  "1T":1%% Taoïstes
  "1 CHRÉTIENS":1:::azul
    "CHRÉTIENS":0:::azul
    "CATHOLIQUES":0:::bleu
    "ANGLICANS":0:::ardoise
    "PROTESTANTS":0:::turquoise
  "11 JUIFS":0:::bleu
  "2M":0:::turquoise%% Musulmans
  "1P":0:::menthe%% Panthéistes
  "1D":00:::bleu%% Déiste (Rousseau)
  "15 ATHÉES":::orange
    "ATHÉES":0:::orange
    "MATÉRIALISTES":0:::ardoise
  "14 AGNOSTIQUES":0:::menthe
classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
