---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"RÉPARTITION DES CROYANCES DES PHILOSOPHES MODERNES AU PROGRAMME DE TERMINALE":::menthe
  "11 PAÏENS":0:::ocre
  "1B":0%% Bouddhistes
  "1T":0%% Taoïstes
  "14 CHRÉTIENS":::azul
    "CHRÉTIENS":0:::azul
    "CATHOLIQUES":7:::bleu
    "ANGLICANS":4:::ardoise
    "PROTESTANTS":3:::turquoise
  "1 JUIF":0:::bleu
  "2 MUSULMANS":0:::turquoise%% Musulmans
  "1P":1:::menthe%% Panthéistes
  "1 Déiste":1:::bleu%% Déiste (Rousseau)
  "3 ATHÉES":::orange
    "ATHÉES":1:::orange
    "MATÉRIALISTES":2:::ardoise
  "1 AGNOSTIQUE":1:::menthe
classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
