---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"RÉPARTITION DES CROYANCES DES PHILOSOPHES CONTEMPORAINS IMPORTANTS":::menthe
  "11 PAÏENS":0:::ocre
  "1B":0%% Bouddhistes
  "1T":0%% Taoïstes
  "8 CHRÉTIENS":::azul
    "CHRÉTIENS":0:::azul
    "CATHOLIQUES":35:::bleu
    "ANGLICANS":1:::ardoise
    "PROTESTANTS":11:::turquoise
  "10 JUIFS":10:::bleu
  "2 MUSULMANS":0:::turquoise%% Musulmans
  "1P":0:::menthe%% Panthéistes
  "1 Déiste":0:::bleu%% Déiste (Rousseau)
  "12 ATHÉES":::orange
    "ATHÉES":9:::orange
    "MATÉRIALISTES":3:::ardoise
  "14 AGNOSTIQUES":14:::menthe
classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
