---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"Les 4 principes qui caractérise la Démocratie Directe selon Max WEBER :":::menthe
  "Révocabilité des élus":40:::azul
  "Rotation des charges":40:::turquoise
  "Tirage au sort":40:::orange
  "Mandats Impératifs":40:::ardoise
%% Une autre palette
classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
