---
config:
  theme: forest
---
pie
    title Fonctionnement de l'intelligence
    "Vue d'ensemble (cet article)" : 10
    "La simple appréhension" : 10
    "La querelle des universaux" : 10
    "La définition" : 10
    "Le jugement" : 10
    "La vérité" : 10
    "Le raisonnement" : 10
    "La science" : 10
