---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"La liberté de QUALITÉ se développe dans une substance humaine":::menthe
    "C'est un habitus qui est plus ou moins développé":::azul
      "Spirituel et Corporel":::menthe
        "Qui relève de la volonté (appétit intellectuel)":::turquoise
            "Qui est fort donc qui est choisi = Libre-Arbitre":::menthe
                "Vertueux":92:::turquoise
                "Vicieux":40:::ardoise
            "Qui est faible":::ardoise
              "Réflexe":20:::azul
              "Programmé":20:::ardoise
              "Influencé":18:::bleu
        "Appétit sensitif":::orange
            "Irascible":18:::ocre
            "Concupiscible":18:::orange
            "Imaginatif":20:::marron
            "Mnésique":20:::bleu
      "Spirituel":20:::bleu
      "Corporel":20:::ocre
    "Faculté":20:::orange
classDef important fill:#5F0

classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445

