---
config:
  theme: forest
  themeVariables:
    fontFamily: verdana
---
treemap-beta
%% Diagramme pour la liberté de qualité
"La liberté de QUALITÉ se développe dans une substance humaine"
    "C'est un habitus qui est plus ou moins développé"
    %% J'avais choisi au départ de mettre qualité mais j'ai préféré
    %% le terme d'habitus
      "Spirituel et Corporel"
        "Qui relève de la volonté (appétit intellectuel)"
            "Qui est fort donc choisit = Libre-Arbitre"
                "Vertueux":92:::important
                "Vicieux":40
            "Qui est faible"
              "Réflexe":20
              "Programmé":20
              "Influencé":18
        "Appétit sensitif"
            "Irascible":18
            "Concupiscible":18
            "Imaginatif":20
            "Mnésique":20
      "Spirituel":20
      "Corporel":20
    "Faculté":20
classDef important fill:#5F0