---
config:
  theme: forest
  themeVariables:
    fontFamily: verdana
---
treemap-beta
%% Diagramme pour la liberté d'indifférence :
"La liberté d'INDIFFÉRENCE se développe dans une substance humaine"
    "C'est un habitus qui est plus ou moins développé"
    %% Au départ j'avais mis qualité au lieu de habitus
      "Spirituel et Corporel"
        "Qui relève de la volonté (appétit intellectuel)"
            "Qui est choisi et"
                "Vertueux":42
                "Vicieux":82:::important
            "Réflexe      ":30
            "Programmé":40
        "Appétit sensitif"
            "Irascible    ":20
            "Concupiscible":20
            "Imaginatif   ":20
            "Mnésique     ":20
      "Spirituel":20
      "Corporel":20
    "Faculté":20
classDef important fill:#F50
