---
config:
  theme: default
---
%% Il y a en tout 18 notions en comptant l'œuvre, il faut donc que la somme des 3 premières catégories fasse 18
pie
    title --> Progression d'année au niveau des notions
    "Notions Vues" : 1
    "Notions en cours" : 7
    "Notions futures" : 10
    "Notions révisées" : 0
