---
config:
  theme: base
  themeVariables:
    fontFamily: verdana
---
timeline
    title Agenda des notions au programme pour le cours de philosophie
    section Septembre -> Vacances de la Toussaint
        Introduction : Vertu de tempérance : Philosophe ≠ Sophiste : Méthode de dissertation : Raison : Vérité : Liberté : Bonheur
        Philosophie de la connaissance : Raison : Vérité : Science
        Philosophie morale : Liberté : Conscience
    section Novembre -> Vacances de Noël
        Philosophie morale : Bonheur : Devoir : Inconscient
    section Janvier -> Vacances d'hiver
        Philosophie politique : Méthode d'étude ordonnée : Religion : État et Justice
    section Mars -> Vacances de printemps
        Philosophie de l'existence humaine et de la culture : Temps : Langage : Considérations morales d'Hannah ARENDT : Nature, Travail et Technique
    section Mai -> Libération
        Philosophie de l'existence humaine et de la cutlure : Art
        Révisions
