---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"LES POST-PRÉDICAMENTS QUI MODULENT LES CATÉGORIES DE L'ÊTRE":::bleu
  "1 Opposition":::bleu
    "Contradiction":28:::azul
    "Privation":20:::ardoise
    "Contrariété":20:::turquoise
    "Relation":20:::menthe
  "2 Antérieur & Postérieur":::turquoise
    "Temporels":20:::azul
    "Ontologique":20:::turquoise
    "Logique":20:::bleu
    "Finale":20:::orange
  "3 Simultanéité":20:::azul
  "4 Mouvement":::orange
    "Génération":26:::turquoise
    "Corruption":26:::ardoise
    "Augmentation":26:::menthe
    "Diminution":26:::ocre
    "Altération":20:::azul
    "Mouvement local":::orange
      "Changement":20:::ocre
      "Déplacement":20:::azul
  "5 Avoir":20:::marron
classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
