---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"LES PRÉDICAMENTS OU LES CATÉGORIES DE L'ÊTRE":::menthe
  "1 Substance":::azul
    "Naturelle"
      "PI":14 %% Parties Intégrantes
      "PP":14 %% Parties Potentielles
    "Artificielle":20
    "Hybride":20
  "2 Quantité":::turquoise
    "Quantité":20
    "Mesure":20
  "3 Qualité":::azul
    "Forme":20
    "Puissance":20
 %%   "Impuissance":20
    "Disposition":20
    "Habitus":20
  "4 Relation":::orange
    "Réelle":15
    "De raison":15
  "5 Lieu":20:::ocre
  "6 Position":20:::marron
  "7 Temps":20:::bleu
  "8 Action":::azul
    "Faire":15
    "Agir":15
  "9 Passion":::orange
    "Corporelle":20
    "Animale":20
  "10 Possession":20:::ardoise
%% Une autre palette
classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
