---
config:
  theme: forest
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
---
treemap-beta
"Les prédicables d'une substance"
  "Essentiels"
   "Le genre"
    "genre lointain":20
    "genre prochain":20:::important
   "L'espèce"
    "Genre prochain":20:::important
    "Différence spécifique":20:::important
   "La différence"
    "Différence spécifique":40:::important
   "Le propre"
    "Appartient à l'espèce":40
  "Les accidents"
    "Séparables":20
    "Inséparables":20
"De plusieurs substances"
  "Appartient à un genre"
    "Différence commune":30
    "Les propriétés":22:::dis
classDef important fill:#07F
classDef dis fill:#FFF
