---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
---
treemap-beta
"Les prédicables d'une substance":::bleu
  "Essentiels":::jaune
   "Le genre":::grisclair
    "genre lointain":20:::olive
    "genre prochain":20:::jaune
   "L'espèce":::grisclair
    "Genre prochain":20:::jaune
    "Différence spécifique":20:::brique
   "La différence":::grisclair
    "Différence spécifique":40:::bleuvert
   "Le propre":::grisclair
    "Appartient à l'espèce":40
  "Les accidents":::grisclair
    "Séparables":20:::bleugris
    "Inséparables":20:::grisbleu
"De plusieurs substances":::brun
  "Appartient à un genre":::jaune
    "Différence commune":30
    "Les propriétés":22:::bleunuit

%% J'hésite sur les couleurs à utiliser
%% C'est une ébauche perfectible

%% Palette de 5 couleurs plutôt assortie en ton gris bleu et vert
classDef bleuvert fill:#2F4
classDef bleugris fill:#587
classDef grisclair fill:#BCD
classDef grisbleu fill:#789
classDef bleunuit fill:#345

%% Palette plus contrastée pour accentuer la mémorisation
classDef menthe fill:#AF9
classDef brun fill:#544
classDef jaune fill:#CA6
classDef brique fill:#B76
classDef bleu fill:#67D
classDef olive fill:#676