---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
---
treemap-beta
"Les prédicables d'une substance":::bleu
  "Essentiels":::bleu
   "Le genre":::turquoise
    "genre lointain":20:::turquoise
    "genre prochain":20:::menthe
   "L'espèce":::turquoise
    "Genre prochain":20:::menthe
    "Différence spécifique":20:::ardoise
   "La différence":::turquoise
    "Différence spécifique":40:::ardoise
   "Le propre":::turquoise
    "Appartient à l'espèce":40:::turquoise
  "Les accidents":::orange
    "Séparables":20:::ocre
    "Inséparables":20:::orange
"De plusieurs substances":::azul
  "Appartient à un genre":::azul
    "Différence commune":30:::turquoise
    "Les propriétés":22:::ardoise

%% Une autre palette
classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
