---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
---
treemap-beta
"Les prédicables d'une substance":::bleunuit
  "Essentiels":::bleugris
   "Le genre":::grisclair
    "genre lointain":20:::grisbleu
    "genre prochain":20:::bleuvert
   "L'espèce":::grisclair
    "Genre prochain":20:::bleuvert
    "Différence spécifique":20:::bleuvert
   "La différence":::grisclair
    "Différence spécifique":40:::bleuvert
   "Le propre":::grisclair
    "Appartient à l'espèce":40
  "Les accidents":::grisclair
    "Séparables":20:::bleugris
    "Inséparables":20:::grisbleu
"De plusieurs substances":::grisclair
  "Appartient à un genre":::grisclair
    "Différence commune":30
    "Les propriétés":22:::bleunuit
%% Palette de 5 couleurs plutôt assortie
classDef bleuvert fill:#2F4
classDef bleugris fill:#587
classDef grisclair fill:#BCD
classDef grisbleu fill:#789
classDef bleunuit fill:#345  
