---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"EXEMPLES DE QUALITÉS":::menthe
  "FORMES":::bleu
    "Système sanguin":20:::azul
    "structure atomique":20:::ardoise
    "ADN":20:::turquoise
    "Figures":20:::menthe
    "Configuration":24:::bleu
    "Organisation":20:::ocre
  "PUISSANCES":::turquoise
    "Les facultés":25:::azul
    "Les capacités":30:::turquoise
    "Les aptitudes":25:::bleu
    "Les comportements":28:::orange
  "DISPOSITIONS":::azul
    "Oreille absolue":20:::menthe
    "Être un nez":20:::bleu
  "HABITUS":::menthe
    "Vertu innée":20:::azul
    "Vertu acquise":20:::menthe
    "Vertu infuse":20:::bleu
    "Faire du vélo":20:::orange

classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
