---
config:
  theme: default
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
---
treemap-beta
"Une substance vivante, un homme"
    "Une de ses facultés spirituelles : l'intelligence, elle permet de connaître le réel"
      "La simple appréhension":20
      "Le jugement":20
      "La raison ou le raisonnement"
        "Permet de découvrir le vrai à partir du vrai":20
        "Puissance discursive de découverte de la vérité":20
    "L'autre faculté spirituelle"
      "La volonté"
        "Appétit intellectuel":20
        "Vise le bien":20
