---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
    labelFontSize: 24
---
treemap-beta
"EXEMPLES DE SUBSTANCES":::bleu
  "NATURELLES":::bleu
    "Un animal":20:::azul
    "Un végétal":20:::ardoise
    "Une pierre":20:::turquoise
    "Un humain":20:::menthe
    "Un ange":20:::bleu
    "Un gaz":20:::ocre
  "ARTIFICIELLES":::turquoise
    "Un marteau":20:::azul
    "Une voiture":20:::turquoise
    "Un smartphone":20:::bleu
    "Du plastique":20:::orange
    "Une robe":20:::menthe
    "Une fourchette":20:::ocre
  "HYBRIDES":::azul
    "Un mulet":20:::menthe
    "Du blé OGM":20:::orange
classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
