---
config:
  theme: forest
  fontFamily: verdana
---
treemap-beta
"Une Substance"
    "Matérielle"
      "Organique"
        "Animale"
          "Intelligente"
            "Homme":81
          "Bête":20
        "Végétal":25
      "Inorganique"
        "Minéral":20
        "Gaz     ":20
        "Autres             ":20
    "Immatérielle"
      "Anges      ": 44
"Un accident "
  "Les Accidents": 42