---
config:
  theme: forest
  fontFamily: verdana
---
treemap-beta
"Une Substance"
    "Matériel"
      "Organique"
        "Animal"
          "Intelligent"
            "Homme":81
          "Bête":20
        "Végétal":30
      "Inorganique"
        "Minéral":20
        "Gaz     ":20
        "Autres             ":20
    "Immatérielle"
      "Anges      ": 50
"Un Accident"
    "Quantité": 10
    "Relation": 10
    "Lieu   ": 10
    "Temps    ": 10
    "Position ": 10
    "Passion  ": 10
    "Possesion": 10