---
config:
  theme: neutral
  themeVariables:
    fontFamily: verdana
  treemap:
    showValues: false
---
treemap-beta
"La vérité est une relation de correspondance entre notre esprit et la chose qu'il prétend décrire":::azul
    "Les faux-amis de la vérité"
      "L'accord des esprits":28:::azul
      "L'efficacité":20:::orange
      "Les préjugés":::turquoise
        "La naïveté":20:::menthe
        "L'illusion":20:::ardoise
    "Guérison des faux amis"
      "L'exclusion":28:::azul
      "L'échec":28:::orange
      "L'étonnement":::turquoise
        "Étonnement":10:::menthe
        "Surprise":10
        "Erreur":10
        "Désillusion":10:::ardoise
classDef azul fill:#07F
classDef turquoise fill:#0FC
classDef orange fill:#F70
classDef ocre fill:#963
classDef bleu fill:#37A
classDef menthe fill:#4A9
classDef marron fill:#544
classDef ardoise fill:#445
